### ISSUE TITLE
The link to your blog is dead

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [mikestead/as3urlrequestbuilder#1]
Hi Mike

The link to your blog is dead

Is it now hosted elsewhere or is it all lost :-(

PS.

I'm trying to upload multiple files in AS3 (AIR) and was using code by Eugene Zatepyakin, but his bog is dead as well, and his code has bugs when attempting to upload more than one file.

So I thought I'd try your code.

I will still try it, but its more difficult without an overview as was in your blog.

**Comment by mikestead** [comment]
@rogerclarkmelbourne sorry about that, it's been a while :)

I don't have the blog anymore but have copied over the post to the [README](https://github.com/mikestead/as3urlrequestbuilder/blob/master/README.md).

Hope that helps.

**Comment by rogerclarkmelbourne** [comment]
Thanks Mike

Thats great.
